# Generated by Django 4.2.1 on 2023-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acctnumber', models.CharField(max_length=30)),
                ('Accttype', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
